// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fjVXy43UdloOP2Y0F0BHMiqqBQXzOgg',
    appId: '1:1002907359697:web:19dc30021ece2b98a2a8f0',
    messagingSenderId: '1002907359697',
    projectId: 'myserviceappflutter',
    authDomain: 'myserviceappflutter.firebaseapp.com',
    storageBucket: 'myserviceappflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMVFex2nTxuJFaLV7kTmPCY2M6xDb0co',
    appId: '1:1002907359697:android:b63aa22d5004eeb7a2a8f0',
    messagingSenderId: '1002907359697',
    projectId: 'myserviceappflutter',
    storageBucket: 'myserviceappflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2Zog6etf2BujSF8_T74yDC6BPHhRgzw',
    appId: '1:1002907359697:ios:373d60b395d6d05aa2a8f0',
    messagingSenderId: '1002907359697',
    projectId: 'myserviceappflutter',
    storageBucket: 'myserviceappflutter.firebasestorage.app',
    iosClientId: '1002907359697-oo2pqj25d3bjovo5p8rilcn7i2l9i1ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.myservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2Zog6etf2BujSF8_T74yDC6BPHhRgzw',
    appId: '1:1002907359697:ios:373d60b395d6d05aa2a8f0',
    messagingSenderId: '1002907359697',
    projectId: 'myserviceappflutter',
    storageBucket: 'myserviceappflutter.firebasestorage.app',
    iosClientId: '1002907359697-oo2pqj25d3bjovo5p8rilcn7i2l9i1ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.myservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fjVXy43UdloOP2Y0F0BHMiqqBQXzOgg',
    appId: '1:1002907359697:web:36c7b13cc6660f44a2a8f0',
    messagingSenderId: '1002907359697',
    projectId: 'myserviceappflutter',
    authDomain: 'myserviceappflutter.firebaseapp.com',
    storageBucket: 'myserviceappflutter.firebasestorage.app',
  );
}
